# Model arguments
model_name_or_path: data/norllm-ai-normistral-7b-sft-qlora
torch_dtype: null
use_flash_attention_2: false

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_r: 128
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '[TEXT] ' + message['content'] + ' [TITLE] ' }}\n{% elif message['role'] == 'assistant' %}\n{{ message['content'] + eos_token }}\n\n{% endif %}\n{% endfor %}"
dataset_mixer:
  hugodk-sch/aftonposten_title_prefs: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
loss_type: sigmoid
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: norllm-ai-normistral-7b-align-scan
hub_model_revision: dpo-beta-Z
learning_rate: 5.0e-6
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 924
num_train_epochs: 1
optim: adamw_torch
output_dir: data_lr5e-6/norllm-ai-normistral-7b-align-scan-dpo-beta-X
per_device_train_batch_size: 4
per_device_eval_batch_size: 8
push_to_hub: true
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1